[package]
name = "rcore-fs-devfs"
version = "0.1.0"
authors = ["WangRunji <wangrunji0408@163.com>"]
edition = "2018"

[dependencies]
rcore-fs = { path = "../rcore-fs" }
spin = "0.9"
log = "0.4"
async-trait = "0.1"
